os: linux
dist: xenial
language: python
jobs:
  - os: osx
    language: shell
    env: TWINE_USERNAME=__token__
    install: python3 -m pip install cibuildwheel==1.6.3
    script: python3 -m cibuildwheel --output-dir wheelhouse
    after_success:
      - python3 -m pip install twine
      - python3 -m twine upload wheelhouse/*.whl
  - os: windows
    language: shell
    env: TWINE_USERNAME=__token__
    before_install:
      - choco install python --version 3.8.6
      - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    install:
      - python3 -m pip install certifi cibuildwheel==1.6.3
      - export SSL_CERT_FILE=`python3 -c "import certifi;print(certifi.where())"`
      - echo $SSL_CERT_FILE
    script: python -m cibuildwheel --output-dir wheelhouse
    after_success:
      - python -m pip install twine
      - python -m twine upload wheelhouse/*.whl
notifications:
  slack:
    rooms:
      secure: CdWDgKnfYW7vvvoH3nS3yg3TcNZiYLRUyEp6ukQ4rQiiuR4+ltuvyGyFJWgP8r7VVJ9yHkB0jebCKWLUMsAEt1my33B6eMDEVefovpkdh2eJjGswmm80brt0EJULpgwPOtB1U47Mwca8L5jDW4KSv9RypUFRgn8eHDoWw6LKf5g=
